### ISSUE TITLE
StellarPooledNBT causing crash with Thermal Expansion

### ISSUE THREAD

**Issue by sainagh** [NovaEngineering-Source/StellarCore#22]
The issue shows up with stellarcore-0.5.13. It is not present in prior versions.

The game fails to launch due to a crash that mentions stellarcore's StellarPooledNBT mixin method and thermal expansion.

I suspect this may be an issue with the new MBT optimization that was added in the latest version of the mod.

Crash report is attached.

[Crash-latestStellarCore.txt](https://github.com/user-attachments/files/17636754/Crash-latestStellarCore.txt)

**Comment by sainagh** [comment]
Please let me know if there is anything I can do for debugging

**Comment by KasumiNova** [comment]
can provide a full log?

**Comment by sainagh** [comment]
Here is the full log
[latest.log](https://github.com/user-attachments/files/17654338/latest.log)

**Comment by KasumiNova** [comment]
Maybe mixin is broken by other mods, try disable `NBTPrimitiveConstantsPool` option?

**Comment by sainagh** [comment]
Ok, changing the config removed the crash, thanks for checking!

**Comment by jchung01** [comment]
In this case, it seems to be caused by Mob Population Control (MobPC) loading NBTBase too early (re-entrant transformer). Minimal set of mods to cause a crash is:
- ConfigAnytime 3.0
- MixinBooter 9.2
- MobPC 1.0.0.0
- Stellar Core 1.5.13
- Universal Tweaks 1.13.0

debug.log: https://mclo.gs/XXQmedZ
Removing MobPC or disabling the `NBTPrimitiveConstantsPool` "fixes" it. Re-entrant transformers seems to be a pretty recurring problem with ASM coremods and mixin mods...
